# Generated by Django 2.2.12 on 2025-03-21 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_marksgiven'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('resource_title', models.CharField(max_length=255)),
                ('resource_link', models.URLField()),
                ('resource_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='classroom.Student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
