# Generated by Django 2.2.12 on 2025-03-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_learningstyle_performancegoal_studygroup_studysession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcerecommendation',
            options={},
        ),
        migrations.AddField(
            model_name='resourcerecommendation',
            name='is_youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resourcerecommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='classroom.Student'),
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0.0)),
                ('avg_percentage', models.FloatField(default=0.0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='classroom.Student')),
            ],
            options={
                'ordering': ['-avg_percentage'],
            },
        ),
    ]
