# Generated by Django 2.2.12 on 2025-03-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20250321_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='ai_generated',
        ),
    ]
