# Generated by Django 2.2.12 on 2025-03-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_chatmessage_chatsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='role',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('student', 'Student'), ('ai', 'AI Tutor')], default='ai', max_length=10),
        ),
    ]
