# Generated by Django 2.2.12 on 2025-03-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20250321_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='student',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
