# Generated by Django 2.2.12 on 2025-03-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_remove_chat_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartStudyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('weak_areas', models.TextField(help_text='Areas identified for improvement')),
                ('recommended_hours', models.PositiveIntegerField(default=1, help_text='Recommended study hours per week')),
                ('study_material', models.TextField(help_text='Recommended study materials and resources')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='classroom.Student')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
