# Generated by Django 2.2.12 on 2025-03-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_smartstudyplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartstudyplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='smartstudyplan',
            name='recommended_hours',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='smartstudyplan',
            name='study_material',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='smartstudyplan',
            name='weak_areas',
            field=models.TextField(),
        ),
    ]
