# Generated by Django 2.2.12 on 2025-03-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20250321_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksgiven',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marksgiven',
            name='maximum_marks',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marksgiven',
            name='subject_name',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='resourcerecommendation',
            name='resource_description',
            field=models.TextField(default='Resource description'),
        ),
        migrations.AlterField(
            model_name='resourcerecommendation',
            name='resource_link',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='resourcerecommendation',
            name='resource_title',
            field=models.CharField(default='Resource', max_length=255),
        ),
        migrations.AlterField(
            model_name='resourcerecommendation',
            name='subject_name',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
