# Generated by Django 2.2.12 on 2025-03-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_auto_20250321_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='avg_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='classroom.Student'),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
