# Generated by Django 2.2.12 on 2025-03-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_auto_20250321_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerecommendation',
            name='is_ai_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
