# Generated by Django 2.2.12 on 2025-03-21 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_resourcerecommendation_is_ai_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
