# Generated by Django 2.2.12 on 2025-03-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_studentmarks_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_title', models.CharField(max_length=255)),
                ('career_description', models.TextField()),
                ('match_score', models.FloatField(default=0.0)),
                ('skills_needed', models.TextField(default='')),
                ('education_required', models.CharField(default='', max_length=255)),
                ('resource_link', models.URLField(default='https://www.linkedin.com/jobs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_ai_recommended', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to='classroom.Student')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
    ]
