# Generated by Django 2.2.12 on 2025-03-23 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_careerrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('exam', 'Examination'), ('assignment', 'Assignment Due'), ('holiday', 'Holiday'), ('class', 'Special Class'), ('other', 'Other Event')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='calendar_attachments/')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='classroom.Teacher')),
            ],
            options={
                'ordering': ['event_date', 'title'],
            },
        ),
    ]
