# Generated by Django 2.2.12 on 2025-03-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_academiccalendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccalendar',
            name='event_type',
        ),
    ]
