from django.urls import path
from classroom import views

app_name = 'classroom'

urlpatterns = [
    path('',views.home,name="home"),
    path('contact/',views.contact,name="contact"),
    path('register/',views.register,name="register"),
    path('login/',views.user_login,name="login"),
    path('signup/',views.SignUp,name="signup"),
    path('student_signup/',views.StudentSignUp,name="StudentSignUp"),
    path('teacher_signup/',views.TeacherSignUp,name="TeacherSignUp"),
    path('student_registration/',views.student_registration,name="student_registration"),
    path('teachers/',views.teachers_list,name="teachers_list"),
    path('teacher/<int:teacher_id>/',views.teacher_details,name="teacher_details"),
    path('subject/<int:subject_id>/',views.subject_details,name="subject_details"),
    path('resource/<int:resource_id>/',views.resource_details,name="resource_details"),
    path('update_profile/',views.update_profile,name="update_profile"),
    path('filter_teachers_by_subject/',views.filter_teachers_by_subject,name="filter_teachers_by_subject"),
    path('class_notes_list/<int:subject_id>/',views.class_notes_list,name="class_notes_list"),
    path('ask_doubt/',views.ask_doubt,name="ask_doubt"),
    path('resources_list/<int:subject_id>/',views.resources_list,name="resources_list"),
    path('announcements/',views.announcement_list,name="announcement_list"),
    path('assignment/<int:assignment_id>/',views.assignment_detail,name="assignment_detail"),
    path('marks/',views.marks_list,name="marks_list"),
    path('attendance/',views.attendance_list,name="attendance_list"),
    path('leaderboard/',views.feature_unavailable,name="leaderboard"),
    path('recommended_resources/',views.recommended_resources,name="recommended_resources"),
    path('api/marks_data/',views.marks_data,name="marks_data"),
    path('api/attendance_data/',views.attendance_data,name="attendance_data"),
    path('logout/',views.user_logout,name="logout"),
    path('student_assignment/',views.student_assignment,name="student_assignment"),
    path('class_assignment/',views.class_assignment,name="class_assignment"),
    path('my_teachers/',views.my_teachers,name="my_teachers"),
    path('student/<int:pk>/all_marks',views.StudentAllMarksList.as_view(),name="all_marks_list"),
    path('student/<int:pk>/class_notice',views.class_notice,name="class_notice"),
    path('student/<int:pk>/',views.StudentDetailView.as_view(),name="student_detail"),
    path('teacher/<int:pk>/',views.TeacherDetailView.as_view(),name="teacher_detail"),
    path('teacher/<int:pk>/messages_list',views.messages_list,name="messages_list"),
    path('teacher/class_students_list',views.class_students_list,name="class_students_list"),
    path('change_password/',views.change_password,name="change_password"),
    path('student/<int:pk>/message',views.write_message,name="write_message"),
    path('write_notice',views.add_notice,name="write_notice"),
    path('assignment_list/',views.assignment_list,name="assignment_list"),
    path('upload_assignment/',views.upload_assignment,name="upload_assignment"),
    path('submit_list/',views.submit_list,name="submit_list"),
    path('students_list/',views.students_list,name="students_list"),
    path('student/<int:pk>/add/',views.add_student.as_view(),name="add_student"),
    path('submit_assignment/<int:id>/',views.submit_assignment,name="submit_assignment"),
    path('update_assignment/<int:id>/',views.update_assignment,name="update_assignment"),
    path('assignment_delete/<int:id>/',views.assignment_delete,name="assignment_delete"),
    path('update/student/<int:pk>/',views.StudentUpdateView,name="student_update"),
    path('update/teacher/<int:pk>/',views.TeacherUpdateView,name="teacher_update"),
    path('student/<int:pk>/marks_list',views.student_marks_list,name="student_marks_list"),
    path('student/<int:pk>/enter_marks',views.add_marks,name="enter_marks"),
    path('marks/<int:pk>/update',views.update_marks,name="update_marks"),
    path('marks/<int:pk>/delete',views.delete_marks,name="delete_marks"),
    path('reply_message/<int:message_id>/',views.reply_message,name="reply_message"),
    path('student/<int:pk>/marks/delete/',views.delete_marks,name="delete_marks"),
    path('student/<int:pk>/career_recommendations/',views.career_recommendations,name="career_recommendations"),
    
    # Academic Calendar URLs
    path('calendar/', views.calendar_list, name="calendar_list"),
    path('calendar/<int:pk>/', views.calendar_detail, name="calendar_detail"),
    path('calendar/create/', views.calendar_create, name="calendar_create"),
    path('calendar/<int:pk>/update/', views.calendar_update, name="calendar_update"),
    path('calendar/<int:pk>/delete/', views.calendar_delete, name="calendar_delete"),
]
